version: "3.8"

# Hint: Versions and tags are set in the file ".env"

services:
    reverse-proxy:
        image: nginx:1.21
        ports:
            - 8000:80
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    frontend:
        image: node:16
        working_dir: /frontend
        command: ["yarn", "start"]
        init: true
        # TODO: Remove port
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/frontend
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    backend:
        image: fluidblue/wakeonlan-web-backend:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        init: true
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    mariadb:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: test_password
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - mariadb-data:/var/lib/mysql
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mariadb-data:
